In [110]:
import pandas as pd
import numpy as np

In [111]:
columns=['Class','AGE','SEX','STEROID','ANTIVIRALS','FATIGUE','MALAISE','ANOREXIA','LIVER BIG','LIVER FIRM','SPLEEN PALPABLE','SPIDERS','ASCITES','VARICES','BILIRUBIN','ALK PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']
df=pd.read_csv("../26/hepatitis.csv",names=columns)
df.head()

Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
0      2   30    2       1           2       2       2        2         1   
1      2   50    1       1           2       1       2        2         1   
2      2   78    1       2           2       1       2        2         2   
3      2   31    1       ?           1       2       2        2         2   
4      2   34    1       2           2       2       2        2         2   

  LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN ALK PHOSPHATE  \
0          2               2       2       2       2      1.00            85   
1          2               2       2       2       2      0.90           135   
2          2               2       2       2       2      0.70            96   
3          2               2       2       2       2      0.70            46   
4          2               2       2       2       2      1.00             ?   

  SGOT ALBUMIN PROTIME  HISTOLOGY  
0   18     4.0       ?          1  
1   42     3.5       ?          1  
2   32     4.0       ?          1  
3   52     4.0      80          1  
4  200     4.0       ?          1

In [112]:
df.replace("?",np.nan,inplace=True)

In [113]:
df.head()

Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
0      2   30    2       1           2       2       2        2         1   
1      2   50    1       1           2       1       2        2         1   
2      2   78    1       2           2       1       2        2         2   
3      2   31    1     NaN           1       2       2        2         2   
4      2   34    1       2           2       2       2        2         2   

  LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN ALK PHOSPHATE  \
0          2               2       2       2       2      1.00            85   
1          2               2       2       2       2      0.90           135   
2          2               2       2       2       2      0.70            96   
3          2               2       2       2       2      0.70            46   
4          2               2       2       2       2      1.00           NaN   

  SGOT ALBUMIN PROTIME  HISTOLOGY  
0   18     4.0     NaN          1  
1   42     3.5     NaN          1  
2   32     4.0     NaN          1  
3   52     4.0      80          1  
4  200     4.0     NaN          1

In [114]:
df.isnull().sum()

Class               0
AGE                 0
SEX                 0
STEROID             1
ANTIVIRALS          0
FATIGUE             1
MALAISE             1
ANOREXIA            1
LIVER BIG          10
LIVER FIRM         11
SPLEEN PALPABLE     5
SPIDERS             5
ASCITES             5
VARICES             5
BILIRUBIN           6
ALK PHOSPHATE      29
SGOT                4
ALBUMIN            16
PROTIME            67
HISTOLOGY           0
dtype: int64

In [115]:
df.dtypes

Class               int64
AGE                 int64
SEX                 int64
STEROID            object
ANTIVIRALS          int64
FATIGUE            object
MALAISE            object
ANOREXIA           object
LIVER BIG          object
LIVER FIRM         object
SPLEEN PALPABLE    object
SPIDERS            object
ASCITES            object
VARICES            object
BILIRUBIN          object
ALK PHOSPHATE      object
SGOT               object
ALBUMIN            object
PROTIME            object
HISTOLOGY           int64
dtype: object

In [116]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for column in df.columns:
    if df[column].dtype=="object":
        df[column]=le.fit_transform(df[column].astype(float))

In [117]:
df.dtypes

Class              int64
AGE                int64
SEX                int64
STEROID            int64
ANTIVIRALS         int64
FATIGUE            int64
MALAISE            int64
ANOREXIA           int64
LIVER BIG          int64
LIVER FIRM         int64
SPLEEN PALPABLE    int64
SPIDERS            int64
ASCITES            int64
VARICES            int64
BILIRUBIN          int64
ALK PHOSPHATE      int64
SGOT               int64
ALBUMIN            int64
PROTIME            int64
HISTOLOGY          int64
dtype: object

In [118]:
df.isna().sum()

Class              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER BIG          0
LIVER FIRM         0
SPLEEN PALPABLE    0
SPIDERS            0
ASCITES            0
VARICES            0
BILIRUBIN          0
ALK PHOSPHATE      0
SGOT               0
ALBUMIN            0
PROTIME            0
HISTOLOGY          0
dtype: int64

In [119]:
# Remove rows with negative values
df=df[(df >=0 ).all(axis=1)]

Error correcting (Outlier detection and removal)

In [120]:
mean_values=df.mean()
std_values=df.std()

In [121]:
z_score=(df-mean_values)/std_values

In [122]:
# Remove rows with Z-scores greater than 3 (outliers)
df=df[(np.abs(z_score)<3).all(axis=1)]

In [123]:
df.head()

Class  AGE  SEX  STEROID  ANTIVIRALS  FATIGUE  MALAISE  ANOREXIA  \
0      2   30    2        0           2        1        1         1   
1      2   50    1        0           2        0        1         1   
2      2   78    1        1           2        0        1         1   
3      2   31    1        2           1        1        1         1   
4      2   34    1        1           2        1        1         1   

   LIVER BIG  LIVER FIRM  SPLEEN PALPABLE  SPIDERS  ASCITES  VARICES  \
0          0           1                1        1        1        1   
1          0           1                1        1        1        1   
2          1           1                1        1        1        1   
3          1           1                1        1        1        1   
4          1           1                1        1        1        1   

   BILIRUBIN  ALK PHOSPHATE  SGOT  ALBUMIN  PROTIME  HISTOLOGY  
0          7             33     3       16       44          1  
1          6             57    19       11       44          1  
2          4             39    13       16       44          1  
3          4              6    26       16       39          1  
4          7             83    71       16       44          1

Data transformation

In [124]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [125]:
df_scaled=scaler.fit_transform(df)

In [126]:
df_scaled

array([[ 0.51214752, -0.89598502,  2.93683503, ...,  0.03798288,
         0.79575317, -0.91287093],
       [ 0.51214752,  0.69733707, -0.34050261, ..., -0.67535416,
         0.79575317, -0.91287093],
       [ 0.51214752,  2.92798801, -0.34050261, ...,  0.03798288,
         0.79575317, -0.91287093],
       ...,
       [ 0.51214752,  1.57366423, -0.34050261, ...,  0.18065029,
         0.79575317,  1.09544512],
       [ 0.51214752,  0.93633539,  2.93683503, ...,  0.18065029,
        -1.18434359,  1.09544512],
       [-1.95256242,  0.13967434, -0.34050261, ..., -1.10335638,
        -1.47769126,  1.09544512]])

Build Data model using regression and Naïve Bayes methods for prediction

In [127]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [128]:
x=df.drop('HISTOLOGY',axis=1)
y=df['HISTOLOGY']



In [129]:
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=46)

In [133]:
nv=GaussianNB()
nv.fit(x_train,y_train)

GaussianNB()

In [134]:
nv_pred=nv.predict(x_test)
nv_pred

array([2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64)

In [131]:
lr=LogisticRegression()
lr.fit(x_test,y_test)

c:\Users\Atharva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [135]:
lr_pred=lr.predict(x_test)
lr_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 2, 2, 1, 2, 1, 1], dtype=int64)

In [136]:
print("Nabie bayes accuracy ",accuracy_score(y_test,nv_pred))
print("Logistic Regression accuracy ",accuracy_score(y_test,lr_pred))

Nabie bayes accuracy  0.6451612903225806
Logistic Regression accuracy  0.8387096774193549
